export const products = [
    {
        id: 1,
        title: "HansCamp",
        desc: "Mongo JavaScript Express Bootstrap",
        img: "https://i.imgur.com/AgqZXxQ.png",
        link: "https://hanscamp.herokuapp.com/",
        source: "https://github.com/hcmicaya/YelpCamp2.0",
    },
    {
        id: 2,
        title: "HansStore",
        desc: "React Redux",
        img: "https://i.imgur.com/y4zVnDb.png",
        link: "http://hansstore.herokuapp.com/",
        source: "https://github.com/hcmicaya/crwn-clothing",
    },
    {
        id: 3,
        title: "Memories",
        desc: "React Node.js MongoDB Material-UI",
        img: "https://i.imgur.com/M6NY46V.png",
        link: "https://projectmemories2022.netlify.app/posts",
        source: "https://github.com/hcmicaya/Memories",
    },
    {
        id: 4,
        title: "Bulletin",
        desc: "React Node.js MongoDB AWS",
        img: "https://i.imgur.com/C29iCmU.png",
        link: "http://ec2-54-167-60-52.compute-1.amazonaws.com/",
        source: "https://github.com/hcmicaya/Bulletin",
    },
    {
        id: 5,
        title: "DevCamper API",
        desc: "Node.js Express MongoDB",
        img: "https://i.imgur.com/84HGF4A.jpg",
        link: "https://hcmicaya.github.io/devcamper/",
        source: "https://github.com/hcmicaya/devcamper",
    },
    {
        id: 6,
        title: "E-Comm",
        desc: "Mongo Express JavaScript",
        img: "https://i.imgur.com/jKdhbGD.png",
        link: "https://hans-ecomm.herokuapp.com/",
        source: "https://github.com/hcmicaya/ecomm",
    },
];
